name: Produce and Publish PDF
on: [push]
jobs:
  publish_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set Git Version in Document
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "@@GitHash@@"
          replace: "abc123"
          regex: false
      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: rb-cv.tex
      - name: Upload PDF to S3
        uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-west-1'
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          file-path: './rb-cv.pdf'
          output-file-url: 'true'
          destination-dir: '/'
      - name: Show URL
        run: echo '${{ steps.upload.outputs.file-url }}'
